name: "Build environment setup test"
on:
  push:
    branches:
      - main
  schedule:
    - cron: '7 12 * * 1-5'

jobs:
  RPi:
    name: Setup environment and build on Raspberry Pi
    runs-on: [self-hosted, RPi4Too, BareMetalCppTemplate]

    steps:
    - name: Force clean runner work folder
      run: |
        echo "Cleaning up runner work folder"
        rm -rf ${{github.workspace}}/repo
    - name: Say hello
      run: |
        echo "Hello"
        gcc --version
        which gcc
        lsb_release -a
        cat /etc/os-release
        hostnamectl

    - name: Checkout this repo
      uses: actions/checkout@v4
      with:
        path: repo/head

    - name: Prepare build environment
      working-directory: ${{github.workspace}}/repo/head
      run: |
        bash DevUtils/SetupDevEnv.sh /usr/bin/python

    - name: Add to PATH for rest of job
      run: |
        echo "PATH=${{github.workspace}}/tools/cmake-4.0.3-linux-aarch64/bin:$PATH" >> $GITHUB_ENV

    - name: Configure debug ARMv7M build
      run: |
        cmake --preset ARMv7M-fromLinux-debug -S repo/head

    - name: Configure release ARMv7M build
      run: |
        cmake --preset ARMv7M-fromLinux-release -S repo/head

    - name: Configure debug RPiPico build
      run: |
        cmake --preset RPiPico-fromLinux-debug -S repo/head

    - name: Configure release RPiPico build
      run: |
        cmake --preset RPiPico-fromLinux-release -S repo/head

    - name: Build ARMv7M debug
      run: |
        cmake --build repo/head-bin-ARMv7M-fromLinux-debug --target Template

    - name: Build ARMv7M release
      run: |
        cmake --build repo/head-bin-ARMv7M-fromLinux-release --target Template

    - name: Build RPiPico debug
      run: |
        cmake --build repo/head-bin-RPiPico-fromLinux-debug --target hollow_pi

    - name: Build RPiPico release
      run: |
        cmake --build repo/head-bin-RPiPico-fromLinux-release --target hollow_pi
